# Generated by Django 4.1.7 on 2023-05-07 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('nazwa', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('dostepny', models.BooleanField(default=True)),
                ('utworzenie', models.DateTimeField(auto_now_add=True)),
                ('modyfikacja', models.DateTimeField(auto_now=True)),
                ('modyfikacja_dostepnosci', models.DateTimeField(blank=True, null=True)),
                ('rodzic_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='strona.katalog')),
                ('wlasciciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plik',
            fields=[
                ('nazwa', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('dostepny', models.BooleanField(default=True)),
                ('utworzenie', models.DateTimeField(auto_now_add=True)),
                ('modyfikacja', models.DateTimeField(auto_now=True)),
                ('modyfikacja_dostepnosci', models.DateTimeField(blank=True, null=True)),
                ('tresc', models.TextField()),
                ('rodzic_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='strona.katalog')),
                ('wlasciciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sekcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=100, null=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('utworzenie', models.DateTimeField(auto_now_add=True)),
                ('poczatek', models.PositiveIntegerField()),
                ('koniec', models.PositiveIntegerField()),
                ('rodzaj', models.CharField(choices=[('PROCEDURA', 'Procedura'), ('KOMENTARZ', 'Komentarz'), ('DYREKTYWNY_KOMPILATORA', 'Dyrektywny kompilatora'), ('DEKLARACJE_ZMIENNYCH', 'Deklaracje zmiennych'), ('WSTAWKA_ASM', 'Wstawka asemblerowa')], max_length=30)),
                ('status', models.CharField(choices=[('KOMPILUJE_SIE_Z_OSTRZEZENIAMI', 'Kompiluje się z ostrzeżeniami'), ('KOMPILUJE_SIE_BEZ_OSTRZEZEN', 'Kompiluje się bez ostrzeżeń'), ('NIE_KOMPILUJE_SIE', 'Nie kompiluje się')], max_length=50)),
                ('dane_statusu', models.TextField(blank=True)),
                ('rodzic_plik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strona.plik')),
                ('rodzic_sekcja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='strona.sekcja')),
            ],
        ),
    ]
