# Generated by Django 4.1.7 on 2023-05-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sekcja',
            name='rodzaj',
            field=models.CharField(choices=[('PR', 'Procedura'), ('KO', 'Komentarz'), ('DK', 'Dyrektywny kompilatora'), ('DZ', 'Deklaracje zmiennych'), ('WS', 'Wstawka asemblerowa')], max_length=3),
        ),
        migrations.AlterField(
            model_name='sekcja',
            name='status',
            field=models.CharField(choices=[('Z', 'Kompiluje się z ostrzeżeniami'), ('BEZ', 'Kompiluje się bez ostrzeżeń'), ('NIE', 'Nie kompiluje się')], default='BEZ', max_length=3),
        ),
    ]
